export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';
export const GET_USERS_WITH_HIGHEST_REPUTATION = 'GET_USERS_WITH_HIGHEST_REPUTATION';
export const GET_USERS_WITH_LOWEST_REPUTATION = 'GET_USERS_WITH_LOWEST_REPUTATION';
